name: TDD A9 - ed2025a

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Update
      run: sudo apt update
    - name: Instala valgrind
      run: sudo apt install -y valgrind
    - name: Compila catch
      run: make
    - name: Roda testes no valgrind
      run: valgrind --leak-check=full ./a.out --reporter compact --success
